name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building and pushing the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}  # Only push on push events, not PRs
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rental-data:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/rental-data:${{ github.sha }}  # Tag with commit SHA
          cache-from: type=gha  # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max

      # Optional: Output the image digest
      - name: Output image digest
        run: echo "Image digest: ${{ steps.build-and-push.outputs.digest }}"
