name: Build Docker Image

on:
  push:
    branches: ["main"]
    paths: ["docker/Dockerfile"] # Triggers only when Dockerfile changes

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Login to GHCR (using native GitHub token)
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build and push image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/ # Path to your Dockerfile folder
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. Output image location
      - name: Show image URL
        run: |
          echo "Image pushed to: ghcr.io/${{ github.repository }}"
          echo "You can pull it with:"
          echo "docker pull ghcr.io/${{ github.repository }}:latest"
